version: '3.8'

services:
  db:
    image: postgres:17.1
    ports:
      - 5432:5432
    environment:
      - TZ=Asia/Shanghai
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    restart: unless-stopped

  cache:
    image: redis:7.4
    ports:
      - 6379:6379
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped

  storage:
    image: minio/minio
    command: server /data --console-address ":9001"
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - TZ=Asia/Shanghai
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=admin123
    volumes:
      - ./data/storage:/data
    restart: unless-stopped

  # nocodb:
  #   image: nocodb/nocodb:latest
  #   ports:
  #     - 8080:8080
  #   environment:
  #     - TZ=Asia/Shanghai
  #     - NC_DB=pg://host.docker.internal:5432?u=postgres&p=postgres&d=postgres
  #     - NC_AUTH_JWT_SECRET=56911121-0a93-45e8-87ab-eb857f20a010
  #     - NC_ADMIN_EMAIL=admin@example.com
  #     - NC_ADMIN_PASSWORD=admin123
  #   volumes:
  #     - ./data/nocodb:/usr/app/data/
  #   restart: unless-stopped

