version: '3.8'

services:
  db:
    image: postgres:17.1
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 10s
      retries: 5
    ports:
      - 5432:5432
    environment:
      - TZ=Asia/Shanghai
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    restart: unless-stopped

  cache:
    image: redis:7.4
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-server", "--ping"]
      interval: 3s
      timeout: 10s
      retries: 5
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped

  storage:
    image: minio/minio
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://minio:9000/minio/health/live"]
      interval: 3s
      timeout: 10s
      retries: 5
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - TZ=Asia/Shanghai
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=admin123
    volumes:
      - ./data/storage:/data
    restart: unless-stopped
